### ISSUE TITLE
Wakatime plugin for micro fails to load 

### ISSUE THREAD

**Issue by hcbt** [wakatime/micro-wakatime#1]
Plugin installs successfully, however when I try to run micro with this plugin enabled I get the following error:

```
wakatime:15: attempt to index a non-table object(nil) with key 'String'
stack traceback:
	wakatime:15: in main chunk
	[G]: ?

Press enter to continue
```
Running on Mac OS 11.0.1 Big Sur and 2.0.8 version of Micro.

**Comment by gandarez** [comment]
We've got broken by this [PR](https://github.com/zyedidia/micro/pull/1917). It's still under consideration from the micro-editor owners.

**Comment by gandarez** [comment]
PR has been merged and to get it working you need to build micro from source.

**Comment by hcbt** [comment]
Thanks! Hopefully this will be fixed in the next release of micro and I'll attempt to build it from source until that happens.
