### ISSUE TITLE
Micro not tracking data because wakatime-cli isn't found

### ISSUE THREAD

**Issue by DNAMcKnight** [wakatime/micro-wakatime#10]
here's my log 
```log
2023/01/08 20:50:58 Micro started
2023/01/08 20:50:58 initializing WakaTime v1.0.5
2023/01/08 20:50:58 failed to determine current cli version
2023/01/08 20:50:58 fork/exec /home/mcknight/.wakatime/wakatime-cli/wakatime-cli: not a directory
2023/01/08 20:50:58 WakaTime initialized
```
I followed the instructions and read them carefully but the error presists. I am using Arch Linux, I've installed micro using `yay` and I've tried installing the plugin in every way, my API key is correct but I noticed that `wakatime-cli` is not found. I looked at the `wakatime-cli` repo but it says I only need that when I'm making my own plugins, which I'm not. I would appreciate some help on how I can fix this.

**Comment by alanhamlett** [comment]
Fixed in 938372f20021979cc087c7754f761fb04df269f7 by using new Go wakatime-cli. We'll release a new version soon after adding GitHub API caching.
