### ISSUE TITLE
Error on start: attempt to index a non-table object(nil) with key 'String'

### ISSUE THREAD

**Issue by MostHated** [wakatime/micro-wakatime#4]
Hello,
    I just installed the plugin for Micro, but I am getting the following error when trying to start it up.

```sh
~ » mi ~/.zshrc                                                                                    mosthated@pop-os
wakatime:15: attempt to index a non-table object(nil) with key 'String'
stack traceback:
	wakatime:15: in main chunk
	[G]: ?

Press enter to continue
```
If I attempt to enter: `wakatime.apikey` within the editor using ctrl+e, I get a message stating "Unknown command: wakatime.apikey"

Thanks,
-MH

**Comment by gandarez** [comment]
Which micro version are you using? `./micro --version` to get info.

**Comment by MostHated** [comment]
Here is the output:

```sh
Version: 2.0.8
Commit hash: cfcb2e45
Compiled on October 06, 2020
```

**Comment by gandarez** [comment]
Although the version you're using is the latest one the maintainer didn't bump a new one yet. I suggest you to [build from source ](https://github.com/zyedidia/micro#building-from-source) to get it working as expected.

The commit we added new functions is this https://github.com/zyedidia/micro/commit/7a5f7e443a51455acb307e9212377d7cfaedefac.

**Comment by MostHated** [comment]
Ok, that seems to have done it. I know that it's not really your fault as Micro has not had an official update in a while, but it would certainly be helpful if installing the plugin by following the listed instructions worked for the current version. If nothing else, at least a notice/note in the instructions stating the requirements.

**Comment by gandarez** [comment]
@MostHated a note has been added. Thanks.

https://github.com/wakatime/micro-wakatime#installation

**Comment by MostHated** [comment]
Looks good. Much appreciated. :+1:
